wip: Re-Enabled branding feature for failed check

diff --git a/ops/build/docker/Dockerfile.dev.jinja b/ops/build/docker/Dockerfile.dev.jinja
--- a/ops/build/docker/Dockerfile.dev.jinja
+++ b/ops/build/docker/Dockerfile.dev.jinja
@@ -84,12 +84,12 @@ RUN	chown -R ${IMAGE_USER}:${IMAGE_GROUP} /run/nginx.pid ; \
 
 # Verify changes were made
 RUN set -e; \
-	if [ ! -d '/home/${IMAGE_USER}/bench/apps/{{ app_name }}' ]; then \
-	echo 'Missing app {{ app_name }}'; \
+	if [ ! -d "/home/${IMAGE_USER}/bench/apps/{{ app_name }}" ]; then \
+	echo "Missing app {{ app_name }}"; \
 	exit 1; \
 	fi; \
-	if ! grep -q 'Starting {{ project_name }}' /home/${IMAGE_USER}/bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.js; then \
-	echo 'docker-patches.sh might not have run completely'; \
+	if ! grep -q "Starting {{ project_name }}" "/home/${IMAGE_USER}/bench/apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.js"; then \
+	echo "docker-patches.sh might not have run completely"; \
 	exit 1; \
 	fi
 
